### ISSUE TITLE
高校考试平台军事理论刷课不提交问题，以及一些程序升级建议

### ISSUE THREAD

**Issue by XXXXBully** [AlwaysLazy21/gxks-script#2]
作者你好，有幸用到你的脚本
我使用之后发现程序他最后一分钟不刷，例如视频要求30分钟，他只刷29分钟刷不满
建议能不能加一个通过联系获取题库的答案保存在本地的程序，然后再用于期末自动答题，十分感谢

**Comment by AlwaysLazy21** [comment]
1. 那个脚本出现的问题？可私发我邮箱提供测试账号密码
2. 网上有对应的油猴脚本，刚好符合你的要求

**Comment by XXXXBully** [comment]
> 1. 那个脚本出现的问题？可私发我邮箱提供测试账号密码
> 
>     2. 网上有对应的油猴脚本，刚好符合你的要求

好的我邮箱发你你看看，脚本总会失效，想看看python怎么达到自动答题的需求

**Comment by AlwaysLazy21** [comment]
1. 你提供的账号没有发现未完成的视频任务点，使用代码同时测试了相同前缀的账号，也无相同问题，现将exe重新编译。
2. 目前没有多余的精力去开发新的功能。

**Comment by XXXXBully** [comment]
昨天终极版刷完了，是正常的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月19日(周日) 下午3:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AlwaysLazy21/gxks-script] 高校考试平台军事理论刷课不提交问题，以及一些程序升级建议 (Issue #2)




  
你提供的账号没有发现未完成的视频任务点，使用代码同时测试了相同前缀的账号，也无相同问题，现将exe重新编译。
 
目前没有多余的精力去开发新的功能。
